#!/usr/bin/env bun
// scripts/graphify-sync.mjs
//
// Register this repository's generated Markdown in its own knowledge graph.
//
// THE GAP THIS CLOSES.
//
// `graphify update .` cannot index Markdown. Its help reads "re-extract code
// files and update the graph (no LLM needed)" and its implementation calls
// `_rebuild_code`; it parses code. A session that produces a plan, a batch
// manifest, a spike report, a handoff, a progress log or a learning ledger
// therefore leaves `graphify-out/graph.json` describing only the code it wrote,
// not the documents it generated — and `graphify query` answers questions about
// a repository that, as far as it knows, never wrote anything down.
//
// The fix is the deterministic half of the vault-index pipeline. A note's
// structure — its frontmatter title, its ATX headings, its wikilinks — is
// decidable by a parser, so it costs no model call and no network request. This
// script runs `structural()` over the repo's eligible Markdown and merges the
// resulting nodes into `graphify-out/graph.json` with the same union-by-id
// merger the vault rebuild uses.
//
// WHY THIS IS SAFE IN A REPOSITORY WITH A CLOUD-EXTRACTION BOUNDARY.
//
// `.graphifyignore` GROUP 5 records that a full `graphify extract` here would
// submit document text to a cloud model. This script never calls `extract`,
// never reads an API key, and never opens a socket. It is a local line scan;
// the boundary in `.graphifyignore` is unaffected, and the eligible-file set is
// still decided by graphify's own detector through `scan()`, so the boundary is
// the same one a future `extract` would honour rather than a second
// implementation of it.
//
// THREE THINGS THAT WOULD OTHERWISE GO SILENTLY WRONG.
//
//   1. DUPLICATE DOCUMENT NODES. The graph built by graphify already carries
//      `document` nodes for the notes it once saw, and their ids are graphify's
//      slugs, not this layer's. Merging without reconciling the two id schemes
//      adds a second node for every already-known file and orphans the first
//      one — measured on the vault graph at 1,369 re-attached orphans. So the
//      previous graph's `document` ids are remapped onto this layer's ids for
//      the same `source_file` before the union, exactly as T9 does in
//      `vault-index-rebuild.mjs`.
//
//   2. A LOST CODE GRAPH. `merge()` seeds the union from `previous` first, so
//      every code, concept and rationale node already in the graph is retained
//      and can only be added to. The gate below refuses to write when the node
//      count would fall.
//
//   3. A NON-IDEMPOTENT SECOND RUN. `structural()` is deterministic and the
//      merge is a union keyed on node id, so a second run over unchanged files
//      produces byte-identical output. `--check` is the gate that can tell.
//
// ORDERING: run this AFTER `graphify update .`, never before. `update` rewrites
// the code graph and its writer is not known to preserve foreign nodes; running
// it after this script can discard the document nodes this script just added.
// The end-of-session step in the skill states the order.
//
// Usage:
//   bun scripts/graphify-sync.mjs                 # sync every eligible repo doc, write
//   bun scripts/graphify-sync.mjs <file.md> ...   # sync only those files
//   bun scripts/graphify-sync.mjs --dry-run       # report, write nothing
//   bun scripts/graphify-sync.mjs --check         # exit 1 when the graph is stale
//
// Revert: delete this file and its test, and remove the `graphify:sync` and
// `graphify:check` entries from package.json. The graph is regenerated by
// graphify, and `graphify-out/` is gitignored, so no tracked artifact depends on
// this script. To drop only the document nodes this script added, restore the
// newest `graphify-out/backup-*-sync/graph.json` over `graphify-out/graph.json`.

import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync } from 'node:fs';
import { resolve, join, isAbsolute, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import { scan } from './vault-index.mjs';
import { structural } from './vault-index-structural.mjs';
import { merge, writeGraph, serializeGraph } from './vault-index-merge.mjs';
import { normalizePreviousIds } from './vault-index-rebuild.mjs';

/** The repository root, resolved from this file's own location. */
export const REPO_ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));

/** Where graphify keeps this repository's graph. Gitignored by `.gitignore`. */
export const GRAPH_RELPATH = 'graphify-out/graph.json';

/** The `contains`/`references` structural layer is the only source of doc nodes. */
const STRUCTURAL_CHUNK_NAME = 'structural:repo';

/** A non-empty string, or null. */
function filled(value) {
  return typeof value === 'string' && value.trim() !== '' ? value : null;
}

/**
 * The id this layer will give the document node for each source_file.
 *
 * Document identity is the file, so the map is keyed on `source_file`. Heading
 * nodes also carry `file_type: document` in this layer, so they are skipped by
 * `node_kind`: mapping a file to a heading id would collapse the document node
 * onto one of its own children.
 *
 * First document id wins on a repeated `source_file`, matching
 * `buildIdBySourceFile` in `vault-index-rebuild.mjs`. The emitted chunk is
 * deterministic, so "first" is stable across runs.
 *
 * @param {Array<{chunk?: {nodes?: object[]}}>} chunks
 * @returns {Map<string, string>} source_file -> document node id
 */
export function buildDocIdBySourceFile(chunks) {
  const bySourceFile = new Map();
  for (const entry of chunks ?? []) {
    for (const node of entry?.chunk?.nodes ?? []) {
      if (node?.file_type !== 'document' || node?.node_kind === 'heading') continue;
      const sourceFile = filled(node.source_file);
      if (sourceFile === null || filled(node.id) === null) continue;
      if (!bySourceFile.has(sourceFile)) bySourceFile.set(sourceFile, node.id);
    }
  }
  return bySourceFile;
}

/**
 * Build the merged graph, in memory. No filesystem writes.
 *
 * Split from the CLI so the interesting behaviour is testable without a real
 * graph on disk: `previous` and `files` are inputs, `root` only has to be a real
 * directory holding `files`.
 *
 * @param {{root: string, files: string[], previous: object,
 *   ghostPolicy?: 'drop'|'reattribute'}} opts
 * @returns {{graph: object, idBySourceFile: Map<string, string>,
 *   structuralReport: object, normalization: object, mergeReport: object}}
 */
export function planSync({ root, files, previous, ghostPolicy = 'reattribute' }) {
  if (typeof root !== 'string' || root === '') throw new TypeError(`root must be a non-empty path, got ${JSON.stringify(root)}`);
  if (!Array.isArray(files)) throw new TypeError(`files must be an array, got ${typeof files}`);

  const { chunk, report: structuralReport } = structural(root, files, { knownPaths: files });
  const idBySourceFile = buildDocIdBySourceFile([{ name: STRUCTURAL_CHUNK_NAME, chunk }]);
  const { previous: normalized, report: normalization } = normalizePreviousIds(previous, idBySourceFile);
  const { graph, report: mergeReport } = merge([{ name: STRUCTURAL_CHUNK_NAME, chunk }], {
    previous: normalized,
    ghostPolicy,
  });

  return { graph, idBySourceFile, structuralReport, normalization, mergeReport };
}

/**
 * The gate the write path must pass: no node is lost.
 *
 * A union that only ever grows is the property `merge()` promises, so a falling
 * node count means something upstream is wrong and the graph on disk — the only
 * record of the code extraction — must not be overwritten. `degreeZero` is
 * deliberately NOT gated here: adding isolated document nodes raises it, and
 * that is the expected effect of indexing previously-unindexed files.
 *
 * @param {object} graph
 * @param {{nodes?: object[]}} previous
 */
export function gateVerdict(graph, previous) {
  const nodesBefore = (previous?.nodes ?? []).length;
  const nodesAfter = (graph?.nodes ?? []).length;
  return { pass: nodesAfter >= nodesBefore, nodesBefore, nodesAfter };
}

/**
 * Every eligible Markdown path in the repository, repo-relative and sorted.
 *
 * Eligibility is delegated to graphify's own detector through `scan()`, so the
 * ignore boundary is the one `.gitignore` and `.graphifyignore` already define
 * rather than a second matcher here. PDFs are dropped because `structural()`
 * reads text: a PDF would be counted `filesUnreadable`, not indexed.
 *
 * @param {string} root
 * @returns {string[]}
 */
export function repoDocPaths(root) {
  const { eligible } = scan(root);
  return eligible.filter((p) => /\.(md|mdx)$/i.test(p)).sort();
}

/**
 * Normalise an argv path to a repo-relative path under `root`.
 *
 * Absolute paths are relativised; relative paths are trusted. A path that
 * resolves outside the root is returned as-is so `structural()` reports it
 * `filesOutsideRoot` and emits nothing, rather than this function guessing.
 *
 * @param {string} root
 * @param {string} file
 * @returns {string}
 */
export function toRepoRelative(root, file) {
  if (!isAbsolute(file)) return file;
  return relative(root, file).split('\\').join('/');
}

function readGraph(graphPath) {
  if (!existsSync(graphPath)) {
    throw new Error(
      `no graph at ${graphPath}. This script merges into an existing graph; it does not build one. ` +
        `Run a graphify extraction first, then re-run this sync.`,
    );
  }
  return JSON.parse(readFileSync(graphPath, 'utf8'));
}

function findFlag(argv, flag) {
  return argv.includes(flag);
}

function flagValue(argv, flag) {
  const i = argv.indexOf(flag);
  if (i === -1) return null;
  return argv[i + 1] ?? null;
}

function usage() {
  console.log(`Usage: bun scripts/graphify-sync.mjs [options] [file.md ...]

Registers this repository's Markdown in graphify-out/graph.json as structural
chunk nodes (one document node per file, plus its headings and wikilinks).

Options:
  --dry-run        report what would change, write nothing
  --check          exit 1 when the graph is not already in sync, write nothing
  --root <dir>     repository root (defaults to this repository)
  --graph <path>   graph.json path (defaults to <root>/${GRAPH_RELPATH})
  -h, --help       this message

With no file arguments, every eligible Markdown file in the repository is synced
(eligibility is decided by graphify's own detector, not re-implemented here).
Run this AFTER \`graphify update .\`, never before.`);
}

function main() {
  const argv = process.argv.slice(2);
  if (findFlag(argv, '-h') || findFlag(argv, '--help')) {
    usage();
    return 0;
  }

  const dryRun = findFlag(argv, '--dry-run');
  const check = findFlag(argv, '--check');
  if (dryRun && check) throw new Error('--dry-run and --check are mutually exclusive: both write nothing, but --check has a verdict');

  const root = resolve(flagValue(argv, '--root') ?? REPO_ROOT);
  const graphPath = flagValue(argv, '--graph') ?? join(root, GRAPH_RELPATH);

  // Positional arguments are files. Everything else is a flag or a flag value.
  const positional = [];
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '--root' || a === '--graph') {
      i += 1;
      continue;
    }
    if (a.startsWith('--') || a === '-h') continue;
    positional.push(toRepoRelative(root, a));
  }

  const files = positional.length > 0 ? positional.map((f) => f.trim()).filter(Boolean).sort() : repoDocPaths(root);
  const previous = readGraph(graphPath);
  const { graph, structuralReport, normalization, mergeReport } = planSync({ root, files, previous });
  const gate = gateVerdict(graph, previous);

  console.log('--- graphify-sync ---');
  console.log(`  root:              ${root}`);
  console.log(`  graph:             ${graphPath}`);
  console.log(`  eligible docs:     ${files.length}`);
  console.log(`  files read:        ${structuralReport.filesRead}`);
  console.log(`  files unreadable:  ${structuralReport.filesUnreadable}`);
  console.log(`  files outside:     ${structuralReport.filesOutsideRoot}`);
  console.log(`  document nodes:    ${structuralReport.nodes - structuralReport.headings}`);
  console.log(`  heading nodes:     ${structuralReport.headings}`);
  console.log(`  links:             ${structuralReport.contains + structuralReport.references}`);
  console.log(`  ghost source_file: ${structuralReport.noSourceFile} (must be 0)`);
  console.log(`  old doc ids remapped: ${normalization.documentIdsRemapped}`);
  console.log(`  merge rejected chunks: ${mergeReport.chunksRejected}`);
  console.log(`  nodes:             ${gate.nodesBefore} -> ${gate.nodesAfter}  (must not fall)  ${gate.pass ? 'PASS' : 'FAIL'}`);

  if (structuralReport.noSourceFile !== 0) {
    console.error('REFUSED — the structural layer emitted a node with no source_file. Nothing written.');
    return 1;
  }
  if (!gate.pass) {
    console.error('REFUSED — the merged graph would lose nodes. The graph on disk is untouched.');
    return 1;
  }

  if (check) {
    const expected = serializeGraph(graph);
    const actual = readFileSync(graphPath, 'utf8');
    const current = expected === actual;
    console.log(`  check: ${current ? 'CURRENT' : 'STALE — run without --check to sync'}`);
    return current ? 0 : 1;
  }

  if (dryRun) {
    console.log('DRY RUN — nothing written. Re-run without --dry-run to sync.');
    return 0;
  }

  const stamp = new Date().toISOString().slice(0, 10);
  const backupDir = join(root, 'graphify-out', `backup-${stamp}-sync`);
  mkdirSync(backupDir, { recursive: true });
  copyFileSync(graphPath, join(backupDir, 'graph.json'));
  const written = writeGraph(graph, graphPath);
  console.log(`  backup:            ${backupDir}/graph.json`);
  console.log(`  wrote ${written.path} (${written.bytes} bytes, ${graph.nodes.length} nodes, ${graph.links.length} links)`);
  return 0;
}

if (import.meta.main) {
  try {
    process.exit(main());
  } catch (err) {
    console.error(`graphify-sync: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(2);
  }
}
